env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  semi: 
    - error
    - "always"
  indent:
    - error
    - 2
  react/jsx-uses-react: 
    - 2   
  react/jsx-uses-vars: 
    - error 
  no-unused-vars:
    - off
        

